services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: mlflow_server
    command: ["uv", "run", "mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db"]
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: fastapi_server
    command: ["uv", "run", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: streamlit_app
    command: ["uv", "run", "streamlit", "run", "frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.10.5
    container_name: airflow_server
    command: airflow standalone
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - API_URL=http://api:8000
    depends_on:
      - mlflow
      - api
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
      - ./src:/opt/airflow/src
    restart: unless-stopped

volumes:
  airflow-db:
