FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

# Installation des dépendances (mise en cache)
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project

# Copie de l'ensemble du projet
COPY . .

# Variables d'environnement par défaut
ENV MLFLOW_TRACKING_URI=http://mlflow:5000

# Exposition du port de l'API
EXPOSE 8000

# Commande de démarrage par défaut pour l'API
CMD ["uv", "run", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
