name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: make install

      - name: Download dataset from Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p data
          uvx kaggle datasets download -d anurag629/credit-card-fraud-transaction-data -p data --unzip
          mv data/*.csv data/dataset.csv

      - name: Run Linters (Ruff)
        run: make lint

      - name: Run Type Checking (Mypy)
        run: make type
        
      - name: Run Tests (Pytest)
        run: make test

      - name: Start MLflow server
        run: |
          uv run mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5

      - name: Train model (Optuna)
        run: make train-optuna N_TRIALS=2 CV=3
